timeout: 30m
options:
  logging: GCS_ONLY
logsBucket: ${_BUILD_LOG_BUCKET}
steps:
        - id: 'generate build environment'
          name: 'gcr.io/kaniko-project/executor:latest'
          args:
          - --dockerfile=gcp/Dockerfile
          - --destination=eu.gcr.io/$PROJECT_ID/$_IMAGE_NAME
          - --cache=true
